services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    image: studymint-backend

    ports:
      - "3001:3001"

    env_file:
      - .env

    restart: unless-stopped